dist: trusty
language: javascript
node_js:
  - stable
notifications:
  email:
    recipients:
      - rudinesurya@gmail.com
    on_success: never
    on_failure: always

script:
  - npm run build

deploy:
  provider: firebase
  token:
    secure: 1/tEe0rK73-teoXWnLUIDF5WhGsLmGtMGlJ_ybAwi-BO4
  project: ess-ewd-react
